# Generated by Django 3.1 on 2020-10-10 15:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 15, 10, 26, 674938, tzinfo=utc), verbose_name='ending date'),
        ),
    ]
